// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250717125054_DeletedPokemonMove")]
    partial class DeletedPokemonMove
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Models.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "May paralyze on contact.",
                            Name = "Static"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Powers up Fire-type moves.",
                            Name = "Blaze"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Powers up Water-type moves.",
                            Name = "Torrent"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Powers up Grass-type moves.",
                            Name = "Overgrow"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Prevents loss of accuracy.",
                            Name = "Keen Eye"
                        },
                        new
                        {
                            Id = 6,
                            Description = "May cause infatuation on contact.",
                            Name = "Cute Charm"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Prevents one-hit KO.",
                            Name = "Sturdy"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Eliminates weather effects.",
                            Name = "Cloud Nine"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Passes on status problems.",
                            Name = "Synchronize"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Lowers the foe's Attack stat.",
                            Name = "Intimidate"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.ElementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electric"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Water"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Grass"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Flying"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Normal"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Poison"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Psychic"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ground"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.Evolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromPokemonId")
                        .HasColumnType("int");

                    b.Property<int>("ToPokemonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromPokemonId");

                    b.HasIndex("ToPokemonId");

                    b.ToTable("Evolutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromPokemonId = 4,
                            ToPokemonId = 11
                        },
                        new
                        {
                            Id = 2,
                            FromPokemonId = 2,
                            ToPokemonId = 12
                        },
                        new
                        {
                            Id = 3,
                            FromPokemonId = 3,
                            ToPokemonId = 13
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokedexNumber")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTypeId");

                    b.HasIndex("SecondaryTypeId");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pikachu",
                            PokedexNumber = 25,
                            PrimaryTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Charmander",
                            PokedexNumber = 4,
                            PrimaryTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Squirtle",
                            PokedexNumber = 7,
                            PrimaryTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bulbasaur",
                            PokedexNumber = 1,
                            PrimaryTypeId = 4,
                            SecondaryTypeId = 7
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pidgey",
                            PokedexNumber = 16,
                            PrimaryTypeId = 6,
                            SecondaryTypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jigglypuff",
                            PokedexNumber = 39,
                            PrimaryTypeId = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "Geodude",
                            PokedexNumber = 74,
                            PrimaryTypeId = 9,
                            SecondaryTypeId = 10
                        },
                        new
                        {
                            Id = 8,
                            Name = "Psyduck",
                            PokedexNumber = 54,
                            PrimaryTypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Abra",
                            PokedexNumber = 63,
                            PrimaryTypeId = 8
                        },
                        new
                        {
                            Id = 10,
                            Name = "Growlithe",
                            PokedexNumber = 58,
                            PrimaryTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ivysaur",
                            PokedexNumber = 2,
                            PrimaryTypeId = 4,
                            SecondaryTypeId = 7
                        },
                        new
                        {
                            Id = 12,
                            Name = "Charmeleon",
                            PokedexNumber = 5,
                            PrimaryTypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Wartortle",
                            PokedexNumber = 8,
                            PrimaryTypeId = 3
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.PokemonAbility", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("PokemonAbilities");

                    b.HasData(
                        new
                        {
                            PokemonId = 1,
                            AbilityId = 1
                        },
                        new
                        {
                            PokemonId = 2,
                            AbilityId = 2
                        },
                        new
                        {
                            PokemonId = 3,
                            AbilityId = 3
                        },
                        new
                        {
                            PokemonId = 4,
                            AbilityId = 4
                        },
                        new
                        {
                            PokemonId = 5,
                            AbilityId = 5
                        },
                        new
                        {
                            PokemonId = 6,
                            AbilityId = 6
                        },
                        new
                        {
                            PokemonId = 7,
                            AbilityId = 7
                        },
                        new
                        {
                            PokemonId = 8,
                            AbilityId = 8
                        },
                        new
                        {
                            PokemonId = 9,
                            AbilityId = 9
                        },
                        new
                        {
                            PokemonId = 10,
                            AbilityId = 10
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.Evolution", b =>
                {
                    b.HasOne("Infrastructure.Models.Pokemon", "FromPokemon")
                        .WithMany("Evolutions")
                        .HasForeignKey("FromPokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Models.Pokemon", "ToPokemon")
                        .WithMany()
                        .HasForeignKey("ToPokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromPokemon");

                    b.Navigation("ToPokemon");
                });

            modelBuilder.Entity("Infrastructure.Models.Pokemon", b =>
                {
                    b.HasOne("Infrastructure.Models.ElementType", "PrimaryType")
                        .WithMany()
                        .HasForeignKey("PrimaryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Models.ElementType", "SecondaryType")
                        .WithMany()
                        .HasForeignKey("SecondaryTypeId");

                    b.Navigation("PrimaryType");

                    b.Navigation("SecondaryType");
                });

            modelBuilder.Entity("Infrastructure.Models.PokemonAbility", b =>
                {
                    b.HasOne("Infrastructure.Models.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Models.Pokemon", "Pokemon")
                        .WithMany("Abilities")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("Infrastructure.Models.Pokemon", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Evolutions");
                });
#pragma warning restore 612, 618
        }
    }
}
