// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260109133859_AddedPokemonWeakness")]
    partial class AddedPokemonWeakness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Models.AbilityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "May paralyze on contact.",
                            Name = "Static"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Powers up Fire-type moves.",
                            Name = "Blaze"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Powers up Water-type moves.",
                            Name = "Torrent"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Powers up Grass-type moves.",
                            Name = "Overgrow"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Prevents loss of accuracy.",
                            Name = "Keen Eye"
                        },
                        new
                        {
                            Id = 6,
                            Description = "May cause infatuation on contact.",
                            Name = "Cute Charm"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Prevents one-hit KO.",
                            Name = "Sturdy"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Eliminates weather effects.",
                            Name = "Cloud Nine"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Passes on status problems.",
                            Name = "Synchronize"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Lowers the foe's Attack stat.",
                            Name = "Intimidate"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Inflicts regular damage.",
                            Name = "Scratch"
                        },
                        new
                        {
                            Id = 12,
                            Description = "May inflict a burn.",
                            Name = "Ember"
                        },
                        new
                        {
                            Id = 13,
                            Description = "May inflict a burn.",
                            Name = "Flamethrower"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.ElementTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electric"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Water"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Grass"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Flying"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Normal"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Poison"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Psychic"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ground"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.PokemonAbilityEntity", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("PokemonAbilities");

                    b.HasData(
                        new
                        {
                            PokemonId = 1,
                            AbilityId = 1,
                            RequiredLevel = 15
                        },
                        new
                        {
                            PokemonId = 2,
                            AbilityId = 2,
                            RequiredLevel = 0
                        },
                        new
                        {
                            PokemonId = 3,
                            AbilityId = 3,
                            RequiredLevel = 0
                        },
                        new
                        {
                            PokemonId = 4,
                            AbilityId = 4,
                            RequiredLevel = 0
                        },
                        new
                        {
                            PokemonId = 5,
                            AbilityId = 5,
                            RequiredLevel = 0
                        },
                        new
                        {
                            PokemonId = 6,
                            AbilityId = 6,
                            RequiredLevel = 0
                        },
                        new
                        {
                            PokemonId = 7,
                            AbilityId = 7,
                            RequiredLevel = 0
                        },
                        new
                        {
                            PokemonId = 8,
                            AbilityId = 8,
                            RequiredLevel = 0
                        },
                        new
                        {
                            PokemonId = 9,
                            AbilityId = 9,
                            RequiredLevel = 0
                        },
                        new
                        {
                            PokemonId = 10,
                            AbilityId = 10,
                            RequiredLevel = 0
                        },
                        new
                        {
                            PokemonId = 1,
                            AbilityId = 11,
                            RequiredLevel = 1
                        },
                        new
                        {
                            PokemonId = 1,
                            AbilityId = 12,
                            RequiredLevel = 7
                        },
                        new
                        {
                            PokemonId = 1,
                            AbilityId = 13,
                            RequiredLevel = 15
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.PokemonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokedexNumber")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTypeId");

                    b.HasIndex("SecondaryTypeId");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pikachu",
                            PokedexNumber = 25,
                            PrimaryTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Charmander",
                            PokedexNumber = 4,
                            PrimaryTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Squirtle",
                            PokedexNumber = 7,
                            PrimaryTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bulbasaur",
                            PokedexNumber = 1,
                            PrimaryTypeId = 4,
                            SecondaryTypeId = 7
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pidgey",
                            PokedexNumber = 16,
                            PrimaryTypeId = 6,
                            SecondaryTypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jigglypuff",
                            PokedexNumber = 39,
                            PrimaryTypeId = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "Geodude",
                            PokedexNumber = 74,
                            PrimaryTypeId = 9,
                            SecondaryTypeId = 10
                        },
                        new
                        {
                            Id = 8,
                            Name = "Psyduck",
                            PokedexNumber = 54,
                            PrimaryTypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Abra",
                            PokedexNumber = 63,
                            PrimaryTypeId = 8
                        },
                        new
                        {
                            Id = 10,
                            Name = "Growlithe",
                            PokedexNumber = 58,
                            PrimaryTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ivysaur",
                            PokedexNumber = 2,
                            PrimaryTypeId = 4,
                            SecondaryTypeId = 7
                        },
                        new
                        {
                            Id = 12,
                            Name = "Charmeleon",
                            PokedexNumber = 5,
                            PrimaryTypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Wartortle",
                            PokedexNumber = 8,
                            PrimaryTypeId = 3
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.WeaknessesEntity", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("ElementTypeId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "ElementTypeId");

                    b.HasIndex("ElementTypeId");

                    b.ToTable("Weaknesses");

                    b.HasData(
                        new
                        {
                            PokemonId = 1,
                            ElementTypeId = 10
                        },
                        new
                        {
                            PokemonId = 2,
                            ElementTypeId = 3
                        },
                        new
                        {
                            PokemonId = 2,
                            ElementTypeId = 10
                        },
                        new
                        {
                            PokemonId = 2,
                            ElementTypeId = 9
                        },
                        new
                        {
                            PokemonId = 3,
                            ElementTypeId = 1
                        },
                        new
                        {
                            PokemonId = 3,
                            ElementTypeId = 4
                        },
                        new
                        {
                            PokemonId = 4,
                            ElementTypeId = 2
                        },
                        new
                        {
                            PokemonId = 4,
                            ElementTypeId = 5
                        },
                        new
                        {
                            PokemonId = 4,
                            ElementTypeId = 8
                        },
                        new
                        {
                            PokemonId = 5,
                            ElementTypeId = 1
                        },
                        new
                        {
                            PokemonId = 5,
                            ElementTypeId = 9
                        },
                        new
                        {
                            PokemonId = 7,
                            ElementTypeId = 3
                        },
                        new
                        {
                            PokemonId = 7,
                            ElementTypeId = 4
                        },
                        new
                        {
                            PokemonId = 8,
                            ElementTypeId = 1
                        },
                        new
                        {
                            PokemonId = 8,
                            ElementTypeId = 4
                        },
                        new
                        {
                            PokemonId = 10,
                            ElementTypeId = 3
                        },
                        new
                        {
                            PokemonId = 10,
                            ElementTypeId = 10
                        },
                        new
                        {
                            PokemonId = 10,
                            ElementTypeId = 9
                        },
                        new
                        {
                            PokemonId = 11,
                            ElementTypeId = 2
                        },
                        new
                        {
                            PokemonId = 11,
                            ElementTypeId = 5
                        },
                        new
                        {
                            PokemonId = 11,
                            ElementTypeId = 8
                        },
                        new
                        {
                            PokemonId = 12,
                            ElementTypeId = 3
                        },
                        new
                        {
                            PokemonId = 12,
                            ElementTypeId = 10
                        },
                        new
                        {
                            PokemonId = 12,
                            ElementTypeId = 9
                        },
                        new
                        {
                            PokemonId = 13,
                            ElementTypeId = 1
                        },
                        new
                        {
                            PokemonId = 13,
                            ElementTypeId = 4
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.PokemonAbilityEntity", b =>
                {
                    b.HasOne("Infrastructure.Models.AbilityEntity", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Models.PokemonEntity", "Pokemon")
                        .WithMany("Abilities")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("Infrastructure.Models.PokemonEntity", b =>
                {
                    b.HasOne("Infrastructure.Models.ElementTypeEntity", "PrimaryType")
                        .WithMany()
                        .HasForeignKey("PrimaryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Models.ElementTypeEntity", "SecondaryType")
                        .WithMany()
                        .HasForeignKey("SecondaryTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrimaryType");

                    b.Navigation("SecondaryType");
                });

            modelBuilder.Entity("Infrastructure.Models.WeaknessesEntity", b =>
                {
                    b.HasOne("Infrastructure.Models.ElementTypeEntity", "ElementType")
                        .WithMany()
                        .HasForeignKey("ElementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Models.PokemonEntity", "Pokemon")
                        .WithMany("Weaknesses")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElementType");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("Infrastructure.Models.PokemonEntity", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Weaknesses");
                });
#pragma warning restore 612, 618
        }
    }
}
